/**
 * `qcmp init` — scaffold a starter `qcmp.yaml` from a detected
 * `package.json`. The point is onboarding: get a working inventory in
 * one command so `qcmp list` / `qcmp version` work immediately.
 *
 * Deliberately package.json-only for now (qcmp is the minimal primitive)
 * — other manifests (composer.json, Cargo.toml, …) can be added later.
 * Never clobbers an existing `qcmp.yaml` unless `force` is set.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

export interface InitOptions {
    /** Directory to scaffold in. Default: `QCMP_CWD` or `process.cwd()`. */
    cwd?: string;
    /** Overwrite an existing `qcmp.yaml`. Default false (refuse). */
    force?: boolean;
}

export interface InitResult {
    /** Absolute path of the written `qcmp.yaml`. */
    configPath: string;
    /** `project:` value written (the package name), if any. */
    project?: string;
    /** `key:` of the scaffolded component. */
    componentKey: string;
}

export function initConfig(options: InitOptions = {}): InitResult {
    const cwd = options.cwd ?? process.env.QCMP_CWD ?? process.cwd();
    const configPath = join(cwd, "qcmp.yaml");
    if (existsSync(configPath) && !options.force) {
        throw new Error(
            `qcmp.yaml already exists at ${configPath} — pass --force to overwrite`,
        );
    }
    const pkgPath = join(cwd, "package.json");
    if (!existsSync(pkgPath)) {
        throw new Error(
            `no package.json in ${cwd} — qcmp init scaffolds from package.json; create one first, or write qcmp.yaml by hand`,
        );
    }
    let pkg: { name?: unknown; version?: unknown };
    try {
        pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as typeof pkg;
    } catch (e) {
        throw new Error(`package.json at ${pkgPath} is not valid JSON (${(e as Error).message})`);
    }
    if (typeof pkg.version !== "string") {
        throw new Error(`package.json at ${pkgPath} has no string "version" field to track`);
    }
    const project = typeof pkg.name === "string" && pkg.name ? unscope(pkg.name) : undefined;
    const componentKey = project ?? "app";
    writeFileSync(configPath, renderYaml(project, componentKey), "utf8");
    return { configPath, project, componentKey };
}

/** "@scope/pkg" -> "pkg"; leaves unscoped names untouched. */
function unscope(name: string): string {
    const slash = name.lastIndexOf("/");
    return slash >= 0 ? name.slice(slash + 1) : name;
}

function renderYaml(project: string | undefined, key: string): string {
    const lines = [
        "# Generated by `qcmp init` — edit freely.",
        "# Each component maps a key to a version source. See:",
        "# https://github.com/quazardous/qcmp#readme",
    ];
    if (project) lines.push(`project: ${project}`);
    lines.push(
        "",
        "components:",
        `  - key: ${key}`,
        "    file: package.json",
        "    path: version",
        "    extractor: json",
        "    main: true",
        "",
    );
    return lines.join("\n");
}
